spring.application.name=msferreteriajuncal

spring.datasource.url=jdbc:mysql://localhost:3306/local_ferreteriajuncal
spring.datasource.username=root
spring.datasource.password=paola14032007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Útil para ver mejor los errores en consola
logging.level.ms.msferreteriajuncal=DEBUG
logging.level.org.springframework.web=DEBUG