spring.application.name=msferreteriajuncal
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/local_ferreteriajuncal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=aleja3118

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

logging.level.ms.msferreteriajuncal=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

server.error.include-message=always
server.error.include-binding-errors=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=soporteferreterialaeconomiaayg@gmail.com
spring.mail.password=lzudwaomusduzeij
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

app.mail.from=soporteferreterialaeconomiaayg@gmail.com
app.frontend.reset-url=http://localhost:3000/login?token=
